// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jikgfbpotfsktznmxxvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppa2dmYnBvdGZza3R6bm14eHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2OTc4NzksImV4cCI6MjA1MzI3Mzg3OX0.mOhWIVwYYURGiSiER4ui3UXG7VC3sCsEKekYxgedGgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);